### ISSUE TITLE
Lire le document sur les algos de consensus

### ISSUE THREAD

**Issue by n-peugnet** [lindaAcc/RapidChainDANT#1]
Bon alors qui l'a lu ce doc ??

- [ ] Linda
- [x] Pierre
- [ ] Nicolas

**Comment by n-peugnet** [comment]
oh 'naise il fait 31 pages et c'est en anglais

**Comment by linda-benboudiaf** [comment]
Je ne sais pas si c'est nécéssaire pour l'instant, On s'occupe du prio d'abord. @n-peugnet , @pierrekurz  on est d'accord ?
