### ISSUE TITLE
Distribution

### ISSUE THREAD

**Issue by n-peugnet** [lindaAcc/RapidChainDANT#2]
Todo
-   [x] save and load node hashmap from json file
-   [ ] create a protocol for servers to communicate
    -   [ ] getchain command
    -   [ ] sendblock command

**Comment by linda-benboudiaf** [comment]
TODO
- [x] Finish block RandomGenerator.
- [x] Verify if the BlockChain is valid (Hash current and previous block)
- [ ] Apply Proof-Of-Work
